<?php

return [
    'herald' => [
        'name' => 'CM Herald',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => true,
        'fields' => [],
    ],
    'certification_exam' => [
        'name' => '건설사업관리사자격검정',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_forms' => [
        'name' => 'CM관련서식',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_performance' => [
        'name' => 'CM능력평가공시',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'research' => [
        'name' => '논문 및 연구보고서',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_law' => [
        'name' => '법령정보조회',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'education_seminar' => [
        'name' => '교육 및 세미나사례',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'author_label' => '강사',
        'fields' => [
            // 강사는 작성자(author) 칸 사용. 소속만 metadata로 관리.
            'affiliation' => ['label' => '소속', 'type' => 'text'],
        ],
    ],
    've' => [
        'name' => 'VE자료',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'expert_column' => [
        'name' => '전문가칼럼',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'special_feature' => [
        'name' => '기획/특집',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'etc_data' => [
        'name' => '기타자료',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'press' => [
        'name' => '언론보도',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_overseas' => [
        'name' => 'CM해외공급사업',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_case' => [
        'name' => '수행사례',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'show_metadata' => true,
        'fields' => [
            'orderer' => ['label' => '발주자', 'type' => 'text'],
            'cm_manager' => ['label' => '건설사업관리자', 'type' => 'text'],
        ],
    ],
    'education' => [
        'name' => '교육자료',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_domestic' => [
        'name' => '국내외소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_bid' => [
        'name' => '입찰소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [
            'ordering_office' => ['label' => '발주자', 'type' => 'text', 'placeholder' => '예: 한국철도공사'],
            'announcement_date' => ['label' => '공고일', 'type' => 'date'],
            'deadline_date' => ['label' => '마감일', 'type' => 'date'],
        ],
        'show_metadata' => true,
    ],
    'news_org' => [
        'name' => '유관기관소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_law' => [
        'name' => '법령소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [
            'law_category' => ['label' => '법령 구분', 'type' => 'select', 'options' => [
                'law' => '법·시행령·시행규칙',
                'rule' => '훈령·지침·고시',
                'preview' => '입법예고',
            ]],
        ],
    ],
    'news_association' => [
        'name' => '협회소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_press' => [
        'name' => '보도자료',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_personnel' => [
        'name' => '인사경조사',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'member_trend' => [
        'name' => '회원동향',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'online_news' => [
        'name' => '온라인뉴스',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'schedule' => [
        'name' => '주요행사일정',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'faq' => [
        'name' => 'FAQ',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'free_board' => [
        'name' => '자유게시판',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
        'thread_order' => true, // 원본 스레드 순서(sort_order)로 정렬 (scripts/apply_free_board_order.php 참조)
    ],
    'survey' => [
        'name' => '설문조사',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'book_review' => [
        'name' => 'Book Review',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [
            'book_title' => ['label' => '책제목', 'type' => 'text'],
            'book_author' => ['label' => '저자', 'type' => 'text'],
            'publisher' => ['label' => '출판사', 'type' => 'text'],
        ],
        'show_metadata' => true,
    ],
    'wordbook' => [
        'name' => 'Word Book',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'gallery' => [
        'name' => '사진갤러리',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'job_offer' => [
        'name' => '구인',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [
            'company' => ['label' => '회사명', 'type' => 'text'],
            'company_address' => ['label' => '회사주소', 'type' => 'text'],
            'contact' => ['label' => '연락처', 'type' => 'text'],
            'manager' => ['label' => '담당자', 'type' => 'text'],
            'region' => ['label' => '근무지역', 'type' => 'text'],
            'employment_type' => ['label' => '고용형태', 'type' => 'text'],
            'career' => ['label' => '경력구분', 'type' => 'text'],
            'education' => ['label' => '최종학력', 'type' => 'text'],
            'salary' => ['label' => '급여조건', 'type' => 'text'],
            // 원본 데이터에 '충원시까지' 등 텍스트 값이 있어 date 대신 text 사용
            'deadline' => ['label' => '마감일', 'type' => 'text', 'placeholder' => '예: 26.03.31 또는 충원시까지'],
            // 모집내용은 게시글 본문(content)으로 관리
        ],
        'show_metadata' => true,
    ],
    'job_seek' => [
        'name' => '구직',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [
            'region' => ['label' => '지역', 'type' => 'text'],
            'age' => ['label' => '연령', 'type' => 'text'],
            'desired_job' => ['label' => '희망직종', 'type' => 'text'],
        ],
        'show_metadata' => true,
    ],
];
