<?php

return [
    'herald' => [
        'name' => '회보',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => true,
        'fields' => [],
    ],
    'certification_exam' => [
        'name' => '자격검정시험',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_forms' => [
        'name' => 'CM관련서식',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_performance' => [
        'name' => 'CM능력평가/공시',
        'menu' => '협회업무',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'research' => [
        'name' => '연구자료',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_law' => [
        'name' => 'CM관련법령',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'education_seminar' => [
        'name' => '교육세미나',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    've' => [
        'name' => 'VE자료',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'expert_column' => [
        'name' => '전문가칼럼',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'special_feature' => [
        'name' => '특집',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'etc_data' => [
        'name' => '기타자료',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'press' => [
        'name' => '언론보도',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'cm_case' => [
        'name' => 'CM사례',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'education' => [
        'name' => '교육자료',
        'menu' => 'CM자료방',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_domestic' => [
        'name' => '국내외소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_bid' => [
        'name' => '입찰소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_law' => [
        'name' => '법령소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_association' => [
        'name' => '협회소식',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'news_press' => [
        'name' => '보도자료',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'member_trend' => [
        'name' => '회원동향',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'online_news' => [
        'name' => '온라인뉴스',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'schedule' => [
        'name' => '주요행사일정',
        'menu' => '알림마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'faq' => [
        'name' => 'FAQ',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'free_board' => [
        'name' => '자유게시판',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'survey' => [
        'name' => '설문조사',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'book_review' => [
        'name' => 'BookReview',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => true,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'wordbook' => [
        'name' => 'CM용어사전',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'gallery' => [
        'name' => '사진갤러리',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'job_offer' => [
        'name' => '구인',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
    'job_seek' => [
        'name' => '구직',
        'menu' => '참여마당',
        'category' => null,
        'has_attachments' => true,
        'has_summary' => false,
        'has_issue_number' => false,
        'fields' => [],
    ],
];
